/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HomeResponse } from './HomeResponse';
import {
    HomeResponseFromJSON,
    HomeResponseFromJSONTyped,
    HomeResponseToJSON,
    HomeResponseToJSONTyped,
} from './HomeResponse';

/**
 * 
 * @export
 * @interface CommonResponseHomeResponse
 */
export interface CommonResponseHomeResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseHomeResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseHomeResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseHomeResponse
     */
    message: string;
    /**
     * 
     * @type {HomeResponse}
     * @memberof CommonResponseHomeResponse
     */
    data?: HomeResponse;
}

/**
 * Check if a given object implements the CommonResponseHomeResponse interface.
 */
export function instanceOfCommonResponseHomeResponse(value: object): value is CommonResponseHomeResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseHomeResponseFromJSON(json: any): CommonResponseHomeResponse {
    return CommonResponseHomeResponseFromJSONTyped(json, false);
}

export function CommonResponseHomeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseHomeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : HomeResponseFromJSON(json['data']),
    };
}

export function CommonResponseHomeResponseToJSON(json: any): CommonResponseHomeResponse {
    return CommonResponseHomeResponseToJSONTyped(json, false);
}

export function CommonResponseHomeResponseToJSONTyped(value?: CommonResponseHomeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': HomeResponseToJSON(value['data']),
    };
}

