/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiaryCreateResponse } from './DiaryCreateResponse';
import {
    DiaryCreateResponseFromJSON,
    DiaryCreateResponseFromJSONTyped,
    DiaryCreateResponseToJSON,
    DiaryCreateResponseToJSONTyped,
} from './DiaryCreateResponse';

/**
 * 
 * @export
 * @interface CommonResponseDiaryCreateResponse
 */
export interface CommonResponseDiaryCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseDiaryCreateResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseDiaryCreateResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseDiaryCreateResponse
     */
    message: string;
    /**
     * 
     * @type {DiaryCreateResponse}
     * @memberof CommonResponseDiaryCreateResponse
     */
    data?: DiaryCreateResponse;
}

/**
 * Check if a given object implements the CommonResponseDiaryCreateResponse interface.
 */
export function instanceOfCommonResponseDiaryCreateResponse(value: object): value is CommonResponseDiaryCreateResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseDiaryCreateResponseFromJSON(json: any): CommonResponseDiaryCreateResponse {
    return CommonResponseDiaryCreateResponseFromJSONTyped(json, false);
}

export function CommonResponseDiaryCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseDiaryCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : DiaryCreateResponseFromJSON(json['data']),
    };
}

export function CommonResponseDiaryCreateResponseToJSON(json: any): CommonResponseDiaryCreateResponse {
    return CommonResponseDiaryCreateResponseToJSONTyped(json, false);
}

export function CommonResponseDiaryCreateResponseToJSONTyped(value?: CommonResponseDiaryCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': DiaryCreateResponseToJSON(value['data']),
    };
}

