/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiaryFindAllResponse } from './DiaryFindAllResponse';
import {
    DiaryFindAllResponseFromJSON,
    DiaryFindAllResponseFromJSONTyped,
    DiaryFindAllResponseToJSON,
    DiaryFindAllResponseToJSONTyped,
} from './DiaryFindAllResponse';

/**
 * 
 * @export
 * @interface CommonResponseDiaryFindAllResponse
 */
export interface CommonResponseDiaryFindAllResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseDiaryFindAllResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseDiaryFindAllResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseDiaryFindAllResponse
     */
    message: string;
    /**
     * 
     * @type {DiaryFindAllResponse}
     * @memberof CommonResponseDiaryFindAllResponse
     */
    data?: DiaryFindAllResponse;
}

/**
 * Check if a given object implements the CommonResponseDiaryFindAllResponse interface.
 */
export function instanceOfCommonResponseDiaryFindAllResponse(value: object): value is CommonResponseDiaryFindAllResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseDiaryFindAllResponseFromJSON(json: any): CommonResponseDiaryFindAllResponse {
    return CommonResponseDiaryFindAllResponseFromJSONTyped(json, false);
}

export function CommonResponseDiaryFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseDiaryFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : DiaryFindAllResponseFromJSON(json['data']),
    };
}

export function CommonResponseDiaryFindAllResponseToJSON(json: any): CommonResponseDiaryFindAllResponse {
    return CommonResponseDiaryFindAllResponseToJSONTyped(json, false);
}

export function CommonResponseDiaryFindAllResponseToJSONTyped(value?: CommonResponseDiaryFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': DiaryFindAllResponseToJSON(value['data']),
    };
}

