/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserScaleFindAllResponse } from './UserScaleFindAllResponse';
import {
    UserScaleFindAllResponseFromJSON,
    UserScaleFindAllResponseFromJSONTyped,
    UserScaleFindAllResponseToJSON,
    UserScaleFindAllResponseToJSONTyped,
} from './UserScaleFindAllResponse';

/**
 * 
 * @export
 * @interface CommonResponseUserScaleFindAllResponse
 */
export interface CommonResponseUserScaleFindAllResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseUserScaleFindAllResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseUserScaleFindAllResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseUserScaleFindAllResponse
     */
    message: string;
    /**
     * 
     * @type {UserScaleFindAllResponse}
     * @memberof CommonResponseUserScaleFindAllResponse
     */
    data?: UserScaleFindAllResponse;
}

/**
 * Check if a given object implements the CommonResponseUserScaleFindAllResponse interface.
 */
export function instanceOfCommonResponseUserScaleFindAllResponse(value: object): value is CommonResponseUserScaleFindAllResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseUserScaleFindAllResponseFromJSON(json: any): CommonResponseUserScaleFindAllResponse {
    return CommonResponseUserScaleFindAllResponseFromJSONTyped(json, false);
}

export function CommonResponseUserScaleFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseUserScaleFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : UserScaleFindAllResponseFromJSON(json['data']),
    };
}

export function CommonResponseUserScaleFindAllResponseToJSON(json: any): CommonResponseUserScaleFindAllResponse {
    return CommonResponseUserScaleFindAllResponseToJSONTyped(json, false);
}

export function CommonResponseUserScaleFindAllResponseToJSONTyped(value?: CommonResponseUserScaleFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': UserScaleFindAllResponseToJSON(value['data']),
    };
}

