/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonResponseUnit
 */
export interface CommonResponseUnit {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseUnit
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseUnit
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseUnit
     */
    message: string;
}

/**
 * Check if a given object implements the CommonResponseUnit interface.
 */
export function instanceOfCommonResponseUnit(value: object): value is CommonResponseUnit {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseUnitFromJSON(json: any): CommonResponseUnit {
    return CommonResponseUnitFromJSONTyped(json, false);
}

export function CommonResponseUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseUnit {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
    };
}

export function CommonResponseUnitToJSON(json: any): CommonResponseUnit {
    return CommonResponseUnitToJSONTyped(json, false);
}

export function CommonResponseUnitToJSONTyped(value?: CommonResponseUnit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
    };
}

