/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrentUserResponse } from './CurrentUserResponse';
import {
    CurrentUserResponseFromJSON,
    CurrentUserResponseFromJSONTyped,
    CurrentUserResponseToJSON,
    CurrentUserResponseToJSONTyped,
} from './CurrentUserResponse';

/**
 * 
 * @export
 * @interface CommonResponseCurrentUserResponse
 */
export interface CommonResponseCurrentUserResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseCurrentUserResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseCurrentUserResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseCurrentUserResponse
     */
    message: string;
    /**
     * 
     * @type {CurrentUserResponse}
     * @memberof CommonResponseCurrentUserResponse
     */
    data?: CurrentUserResponse;
}

/**
 * Check if a given object implements the CommonResponseCurrentUserResponse interface.
 */
export function instanceOfCommonResponseCurrentUserResponse(value: object): value is CommonResponseCurrentUserResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseCurrentUserResponseFromJSON(json: any): CommonResponseCurrentUserResponse {
    return CommonResponseCurrentUserResponseFromJSONTyped(json, false);
}

export function CommonResponseCurrentUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseCurrentUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : CurrentUserResponseFromJSON(json['data']),
    };
}

export function CommonResponseCurrentUserResponseToJSON(json: any): CommonResponseCurrentUserResponse {
    return CommonResponseCurrentUserResponseToJSONTyped(json, false);
}

export function CommonResponseCurrentUserResponseToJSONTyped(value?: CommonResponseCurrentUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': CurrentUserResponseToJSON(value['data']),
    };
}

