/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiaryDetailResponse } from './DiaryDetailResponse';
import {
    DiaryDetailResponseFromJSON,
    DiaryDetailResponseFromJSONTyped,
    DiaryDetailResponseToJSON,
    DiaryDetailResponseToJSONTyped,
} from './DiaryDetailResponse';

/**
 * 
 * @export
 * @interface CommonResponseDiaryDetailResponse
 */
export interface CommonResponseDiaryDetailResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseDiaryDetailResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseDiaryDetailResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseDiaryDetailResponse
     */
    message: string;
    /**
     * 
     * @type {DiaryDetailResponse}
     * @memberof CommonResponseDiaryDetailResponse
     */
    data?: DiaryDetailResponse;
}

/**
 * Check if a given object implements the CommonResponseDiaryDetailResponse interface.
 */
export function instanceOfCommonResponseDiaryDetailResponse(value: object): value is CommonResponseDiaryDetailResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseDiaryDetailResponseFromJSON(json: any): CommonResponseDiaryDetailResponse {
    return CommonResponseDiaryDetailResponseFromJSONTyped(json, false);
}

export function CommonResponseDiaryDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseDiaryDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : DiaryDetailResponseFromJSON(json['data']),
    };
}

export function CommonResponseDiaryDetailResponseToJSON(json: any): CommonResponseDiaryDetailResponse {
    return CommonResponseDiaryDetailResponseToJSONTyped(json, false);
}

export function CommonResponseDiaryDetailResponseToJSONTyped(value?: CommonResponseDiaryDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': DiaryDetailResponseToJSON(value['data']),
    };
}

