/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiaryDatesResponse } from './DiaryDatesResponse';
import {
    DiaryDatesResponseFromJSON,
    DiaryDatesResponseFromJSONTyped,
    DiaryDatesResponseToJSON,
    DiaryDatesResponseToJSONTyped,
} from './DiaryDatesResponse';

/**
 * 
 * @export
 * @interface CommonResponseDiaryDatesResponse
 */
export interface CommonResponseDiaryDatesResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseDiaryDatesResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseDiaryDatesResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseDiaryDatesResponse
     */
    message: string;
    /**
     * 
     * @type {DiaryDatesResponse}
     * @memberof CommonResponseDiaryDatesResponse
     */
    data?: DiaryDatesResponse;
}

/**
 * Check if a given object implements the CommonResponseDiaryDatesResponse interface.
 */
export function instanceOfCommonResponseDiaryDatesResponse(value: object): value is CommonResponseDiaryDatesResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseDiaryDatesResponseFromJSON(json: any): CommonResponseDiaryDatesResponse {
    return CommonResponseDiaryDatesResponseFromJSONTyped(json, false);
}

export function CommonResponseDiaryDatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseDiaryDatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : DiaryDatesResponseFromJSON(json['data']),
    };
}

export function CommonResponseDiaryDatesResponseToJSON(json: any): CommonResponseDiaryDatesResponse {
    return CommonResponseDiaryDatesResponseToJSONTyped(json, false);
}

export function CommonResponseDiaryDatesResponseToJSONTyped(value?: CommonResponseDiaryDatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': DiaryDatesResponseToJSON(value['data']),
    };
}

