/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRegisterResponse } from './UserRegisterResponse';
import {
    UserRegisterResponseFromJSON,
    UserRegisterResponseFromJSONTyped,
    UserRegisterResponseToJSON,
    UserRegisterResponseToJSONTyped,
} from './UserRegisterResponse';

/**
 * 
 * @export
 * @interface CommonResponseUserRegisterResponse
 */
export interface CommonResponseUserRegisterResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseUserRegisterResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseUserRegisterResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseUserRegisterResponse
     */
    message: string;
    /**
     * 
     * @type {UserRegisterResponse}
     * @memberof CommonResponseUserRegisterResponse
     */
    data?: UserRegisterResponse;
}

/**
 * Check if a given object implements the CommonResponseUserRegisterResponse interface.
 */
export function instanceOfCommonResponseUserRegisterResponse(value: object): value is CommonResponseUserRegisterResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseUserRegisterResponseFromJSON(json: any): CommonResponseUserRegisterResponse {
    return CommonResponseUserRegisterResponseFromJSONTyped(json, false);
}

export function CommonResponseUserRegisterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseUserRegisterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : UserRegisterResponseFromJSON(json['data']),
    };
}

export function CommonResponseUserRegisterResponseToJSON(json: any): CommonResponseUserRegisterResponse {
    return CommonResponseUserRegisterResponseToJSONTyped(json, false);
}

export function CommonResponseUserRegisterResponseToJSONTyped(value?: CommonResponseUserRegisterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': UserRegisterResponseToJSON(value['data']),
    };
}

