/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 일기 생성 응답
 * @export
 * @interface DiaryCreateResponse
 */
export interface DiaryCreateResponse {
    /**
     * AI가 생성한 일기 요약
     * @type {string}
     * @memberof DiaryCreateResponse
     */
    summary: string;
}

/**
 * Check if a given object implements the DiaryCreateResponse interface.
 */
export function instanceOfDiaryCreateResponse(value: object): value is DiaryCreateResponse {
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function DiaryCreateResponseFromJSON(json: any): DiaryCreateResponse {
    return DiaryCreateResponseFromJSONTyped(json, false);
}

export function DiaryCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiaryCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'summary': json['summary'],
    };
}

export function DiaryCreateResponseToJSON(json: any): DiaryCreateResponse {
    return DiaryCreateResponseToJSONTyped(json, false);
}

export function DiaryCreateResponseToJSONTyped(value?: DiaryCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'summary': value['summary'],
    };
}

