/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecommendedQuestionUserScoreDto } from './RecommendedQuestionUserScoreDto';
import {
    RecommendedQuestionUserScoreDtoFromJSON,
    RecommendedQuestionUserScoreDtoFromJSONTyped,
    RecommendedQuestionUserScoreDtoToJSON,
    RecommendedQuestionUserScoreDtoToJSONTyped,
} from './RecommendedQuestionUserScoreDto';

/**
 * 일기 상세 조회 응답
 * @export
 * @interface DiaryDetailResponse
 */
export interface DiaryDetailResponse {
    /**
     * 일기 ID
     * @type {string}
     * @memberof DiaryDetailResponse
     */
    diaryId: string;
    /**
     * 일기 작성 날짜
     * @type {Date}
     * @memberof DiaryDetailResponse
     */
    date: Date;
    /**
     * 일기 내용
     * @type {string}
     * @memberof DiaryDetailResponse
     */
    content: string;
    /**
     * 감정 상태
     * @type {string}
     * @memberof DiaryDetailResponse
     */
    emotion: DiaryDetailResponseEmotionEnum;
    /**
     * 추천 질문에 대한 사용자 점수 목록
     * @type {Array<RecommendedQuestionUserScoreDto>}
     * @memberof DiaryDetailResponse
     */
    questionScores: Array<RecommendedQuestionUserScoreDto>;
}


/**
 * @export
 */
export const DiaryDetailResponseEmotionEnum = {
    Happy: 'HAPPY',
    Love: 'LOVE',
    Sad: 'SAD'
} as const;
export type DiaryDetailResponseEmotionEnum = typeof DiaryDetailResponseEmotionEnum[keyof typeof DiaryDetailResponseEmotionEnum];


/**
 * Check if a given object implements the DiaryDetailResponse interface.
 */
export function instanceOfDiaryDetailResponse(value: object): value is DiaryDetailResponse {
    if (!('diaryId' in value) || value['diaryId'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('emotion' in value) || value['emotion'] === undefined) return false;
    if (!('questionScores' in value) || value['questionScores'] === undefined) return false;
    return true;
}

export function DiaryDetailResponseFromJSON(json: any): DiaryDetailResponse {
    return DiaryDetailResponseFromJSONTyped(json, false);
}

export function DiaryDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiaryDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'diaryId': json['diaryId'],
        'date': (new Date(json['date'])),
        'content': json['content'],
        'emotion': json['emotion'],
        'questionScores': ((json['questionScores'] as Array<any>).map(RecommendedQuestionUserScoreDtoFromJSON)),
    };
}

export function DiaryDetailResponseToJSON(json: any): DiaryDetailResponse {
    return DiaryDetailResponseToJSONTyped(json, false);
}

export function DiaryDetailResponseToJSONTyped(value?: DiaryDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'diaryId': value['diaryId'],
        'date': value['date'].toISOString().substring(0,10),
        'content': value['content'],
        'emotion': value['emotion'],
        'questionScores': ((value['questionScores'] as Array<any>).map(RecommendedQuestionUserScoreDtoToJSON)),
    };
}

