/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiaryDto } from './DiaryDto';
import {
    DiaryDtoFromJSON,
    DiaryDtoFromJSONTyped,
    DiaryDtoToJSON,
    DiaryDtoToJSONTyped,
} from './DiaryDto';

/**
 * 일기 목록 조회 응답
 * @export
 * @interface DiaryFindAllResponse
 */
export interface DiaryFindAllResponse {
    /**
     * 일기 목록
     * @type {Array<DiaryDto>}
     * @memberof DiaryFindAllResponse
     */
    diaries: Array<DiaryDto>;
}

/**
 * Check if a given object implements the DiaryFindAllResponse interface.
 */
export function instanceOfDiaryFindAllResponse(value: object): value is DiaryFindAllResponse {
    if (!('diaries' in value) || value['diaries'] === undefined) return false;
    return true;
}

export function DiaryFindAllResponseFromJSON(json: any): DiaryFindAllResponse {
    return DiaryFindAllResponseFromJSONTyped(json, false);
}

export function DiaryFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiaryFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'diaries': ((json['diaries'] as Array<any>).map(DiaryDtoFromJSON)),
    };
}

export function DiaryFindAllResponseToJSON(json: any): DiaryFindAllResponse {
    return DiaryFindAllResponseToJSONTyped(json, false);
}

export function DiaryFindAllResponseToJSONTyped(value?: DiaryFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'diaries': ((value['diaries'] as Array<any>).map(DiaryDtoToJSON)),
    };
}

