/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 월별 일기 작성 날짜 목록 응답
 * @export
 * @interface DiaryDatesResponse
 */
export interface DiaryDatesResponse {
    /**
     * 일기가 작성된 날짜 목록
     * @type {Array<Date>}
     * @memberof DiaryDatesResponse
     */
    dates: Array<Date>;
}

/**
 * Check if a given object implements the DiaryDatesResponse interface.
 */
export function instanceOfDiaryDatesResponse(value: object): value is DiaryDatesResponse {
    if (!('dates' in value) || value['dates'] === undefined) return false;
    return true;
}

export function DiaryDatesResponseFromJSON(json: any): DiaryDatesResponse {
    return DiaryDatesResponseFromJSONTyped(json, false);
}

export function DiaryDatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiaryDatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'dates': json['dates'],
    };
}

export function DiaryDatesResponseToJSON(json: any): DiaryDatesResponse {
    return DiaryDatesResponseToJSONTyped(json, false);
}

export function DiaryDatesResponseToJSONTyped(value?: DiaryDatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dates': value['dates'],
    };
}

