/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 일기 요약 정보
 * @export
 * @interface DiaryDto
 */
export interface DiaryDto {
    /**
     * 일기 ID
     * @type {string}
     * @memberof DiaryDto
     */
    diaryId: string;
    /**
     * 일기 작성 날짜
     * @type {Date}
     * @memberof DiaryDto
     */
    date: Date;
    /**
     * 일기 내용
     * @type {string}
     * @memberof DiaryDto
     */
    content: string;
    /**
     * 감정 상태
     * @type {string}
     * @memberof DiaryDto
     */
    emotion: DiaryDtoEmotionEnum;
}


/**
 * @export
 */
export const DiaryDtoEmotionEnum = {
    Happy: 'HAPPY',
    Love: 'LOVE',
    Sad: 'SAD'
} as const;
export type DiaryDtoEmotionEnum = typeof DiaryDtoEmotionEnum[keyof typeof DiaryDtoEmotionEnum];


/**
 * Check if a given object implements the DiaryDto interface.
 */
export function instanceOfDiaryDto(value: object): value is DiaryDto {
    if (!('diaryId' in value) || value['diaryId'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('emotion' in value) || value['emotion'] === undefined) return false;
    return true;
}

export function DiaryDtoFromJSON(json: any): DiaryDto {
    return DiaryDtoFromJSONTyped(json, false);
}

export function DiaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'diaryId': json['diaryId'],
        'date': (new Date(json['date'])),
        'content': json['content'],
        'emotion': json['emotion'],
    };
}

export function DiaryDtoToJSON(json: any): DiaryDto {
    return DiaryDtoToJSONTyped(json, false);
}

export function DiaryDtoToJSONTyped(value?: DiaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'diaryId': value['diaryId'],
        'date': value['date'].toISOString().substring(0,10),
        'content': value['content'],
        'emotion': value['emotion'],
    };
}

