/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuestionScoreItem } from './QuestionScoreItem';
import {
    QuestionScoreItemFromJSON,
    QuestionScoreItemFromJSONTyped,
    QuestionScoreItemToJSON,
    QuestionScoreItemToJSONTyped,
} from './QuestionScoreItem';

/**
 * 일기 생성 요청
 * @export
 * @interface DiaryCreateRequest
 */
export interface DiaryCreateRequest {
    /**
     * 일기 작성 날짜
     * @type {Date}
     * @memberof DiaryCreateRequest
     */
    date: Date;
    /**
     * 일기 내용
     * @type {string}
     * @memberof DiaryCreateRequest
     */
    content: string;
    /**
     * 감정 상태
     * @type {string}
     * @memberof DiaryCreateRequest
     */
    emotion: DiaryCreateRequestEmotionEnum;
    /**
     * 추천 질문에 대한 사용자 점수 목록
     * @type {Array<QuestionScoreItem>}
     * @memberof DiaryCreateRequest
     */
    questionScores: Array<QuestionScoreItem>;
}


/**
 * @export
 */
export const DiaryCreateRequestEmotionEnum = {
    Happy: 'HAPPY',
    Love: 'LOVE',
    Sad: 'SAD'
} as const;
export type DiaryCreateRequestEmotionEnum = typeof DiaryCreateRequestEmotionEnum[keyof typeof DiaryCreateRequestEmotionEnum];


/**
 * Check if a given object implements the DiaryCreateRequest interface.
 */
export function instanceOfDiaryCreateRequest(value: object): value is DiaryCreateRequest {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('emotion' in value) || value['emotion'] === undefined) return false;
    if (!('questionScores' in value) || value['questionScores'] === undefined) return false;
    return true;
}

export function DiaryCreateRequestFromJSON(json: any): DiaryCreateRequest {
    return DiaryCreateRequestFromJSONTyped(json, false);
}

export function DiaryCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiaryCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'content': json['content'],
        'emotion': json['emotion'],
        'questionScores': ((json['questionScores'] as Array<any>).map(QuestionScoreItemFromJSON)),
    };
}

export function DiaryCreateRequestToJSON(json: any): DiaryCreateRequest {
    return DiaryCreateRequestToJSONTyped(json, false);
}

export function DiaryCreateRequestToJSONTyped(value?: DiaryCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'].toISOString().substring(0,10),
        'content': value['content'],
        'emotion': value['emotion'],
        'questionScores': ((value['questionScores'] as Array<any>).map(QuestionScoreItemToJSON)),
    };
}

