/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WelfareServiceItem } from './WelfareServiceItem';
import {
    WelfareServiceItemFromJSON,
    WelfareServiceItemFromJSONTyped,
    WelfareServiceItemToJSON,
    WelfareServiceItemToJSONTyped,
} from './WelfareServiceItem';

/**
 * 홈 화면 정보 응답
 * @export
 * @interface HomeResponse
 */
export interface HomeResponse {
    /**
     * 이번 달 작성한 일기 수
     * @type {number}
     * @memberof HomeResponse
     */
    monthlyDiaryCount: number;
    /**
     * 올해 작성한 일기 수
     * @type {number}
     * @memberof HomeResponse
     */
    yearlyDiaryCount: number;
    /**
     * 감정별 일기 수 (HAPPY, LOVE, SAD)
     * @type {{ [key: string]: number; }}
     * @memberof HomeResponse
     */
    emotionCounts: { [key: string]: number; };
    /**
     * 추천 복지 서비스 목록
     * @type {Array<WelfareServiceItem>}
     * @memberof HomeResponse
     */
    recommendedWelfareServices: Array<WelfareServiceItem>;
    /**
     * 척도 질문 응답 필요 여부
     * @type {boolean}
     * @memberof HomeResponse
     */
    isScaleQuestionRequired: boolean;
    /**
     * 현재 회기 수
     * @type {number}
     * @memberof HomeResponse
     */
    termCount: number;
}

/**
 * Check if a given object implements the HomeResponse interface.
 */
export function instanceOfHomeResponse(value: object): value is HomeResponse {
    if (!('monthlyDiaryCount' in value) || value['monthlyDiaryCount'] === undefined) return false;
    if (!('yearlyDiaryCount' in value) || value['yearlyDiaryCount'] === undefined) return false;
    if (!('emotionCounts' in value) || value['emotionCounts'] === undefined) return false;
    if (!('recommendedWelfareServices' in value) || value['recommendedWelfareServices'] === undefined) return false;
    if (!('isScaleQuestionRequired' in value) || value['isScaleQuestionRequired'] === undefined) return false;
    if (!('termCount' in value) || value['termCount'] === undefined) return false;
    return true;
}

export function HomeResponseFromJSON(json: any): HomeResponse {
    return HomeResponseFromJSONTyped(json, false);
}

export function HomeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HomeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'monthlyDiaryCount': json['monthlyDiaryCount'],
        'yearlyDiaryCount': json['yearlyDiaryCount'],
        'emotionCounts': json['emotionCounts'],
        'recommendedWelfareServices': ((json['recommendedWelfareServices'] as Array<any>).map(WelfareServiceItemFromJSON)),
        'isScaleQuestionRequired': json['isScaleQuestionRequired'],
        'termCount': json['termCount'],
    };
}

export function HomeResponseToJSON(json: any): HomeResponse {
    return HomeResponseToJSONTyped(json, false);
}

export function HomeResponseToJSONTyped(value?: HomeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'monthlyDiaryCount': value['monthlyDiaryCount'],
        'yearlyDiaryCount': value['yearlyDiaryCount'],
        'emotionCounts': value['emotionCounts'],
        'recommendedWelfareServices': ((value['recommendedWelfareServices'] as Array<any>).map(WelfareServiceItemToJSON)),
        'isScaleQuestionRequired': value['isScaleQuestionRequired'],
        'termCount': value['termCount'],
    };
}

