/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 질문 점수 항목
 * @export
 * @interface QuestionScoreItem
 */
export interface QuestionScoreItem {
    /**
     * 질문 텍스트
     * @type {string}
     * @memberof QuestionScoreItem
     */
    questionText: string;
    /**
     * 점수 (0-10)
     * @type {number}
     * @memberof QuestionScoreItem
     */
    score: number;
}

/**
 * Check if a given object implements the QuestionScoreItem interface.
 */
export function instanceOfQuestionScoreItem(value: object): value is QuestionScoreItem {
    if (!('questionText' in value) || value['questionText'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function QuestionScoreItemFromJSON(json: any): QuestionScoreItem {
    return QuestionScoreItemFromJSONTyped(json, false);
}

export function QuestionScoreItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionScoreItem {
    if (json == null) {
        return json;
    }
    return {
        
        'questionText': json['questionText'],
        'score': json['score'],
    };
}

export function QuestionScoreItemToJSON(json: any): QuestionScoreItem {
    return QuestionScoreItemToJSONTyped(json, false);
}

export function QuestionScoreItemToJSONTyped(value?: QuestionScoreItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'questionText': value['questionText'],
        'score': value['score'],
    };
}

