/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 추천 질문 점수
 * @export
 * @interface RecommendedQuestionUserScoreDto
 */
export interface RecommendedQuestionUserScoreDto {
    /**
     * 질문 텍스트
     * @type {string}
     * @memberof RecommendedQuestionUserScoreDto
     */
    questionText: string;
    /**
     * 사용자가 입력한 점수
     * @type {number}
     * @memberof RecommendedQuestionUserScoreDto
     */
    score: number;
}

/**
 * Check if a given object implements the RecommendedQuestionUserScoreDto interface.
 */
export function instanceOfRecommendedQuestionUserScoreDto(value: object): value is RecommendedQuestionUserScoreDto {
    if (!('questionText' in value) || value['questionText'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function RecommendedQuestionUserScoreDtoFromJSON(json: any): RecommendedQuestionUserScoreDto {
    return RecommendedQuestionUserScoreDtoFromJSONTyped(json, false);
}

export function RecommendedQuestionUserScoreDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecommendedQuestionUserScoreDto {
    if (json == null) {
        return json;
    }
    return {
        
        'questionText': json['questionText'],
        'score': json['score'],
    };
}

export function RecommendedQuestionUserScoreDtoToJSON(json: any): RecommendedQuestionUserScoreDto {
    return RecommendedQuestionUserScoreDtoToJSONTyped(json, false);
}

export function RecommendedQuestionUserScoreDtoToJSONTyped(value?: RecommendedQuestionUserScoreDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'questionText': value['questionText'],
        'score': value['score'],
    };
}

