/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScaleQuestionUserAnswerItem } from './ScaleQuestionUserAnswerItem';
import {
    ScaleQuestionUserAnswerItemFromJSON,
    ScaleQuestionUserAnswerItemFromJSONTyped,
    ScaleQuestionUserAnswerItemToJSON,
    ScaleQuestionUserAnswerItemToJSONTyped,
} from './ScaleQuestionUserAnswerItem';

/**
 * 척도 질문 응답 등록 요청
 * @export
 * @interface ScaleQuestionUserAnswerRegisterRequest
 */
export interface ScaleQuestionUserAnswerRegisterRequest {
    /**
     * 척도 질문 응답 항목 목록
     * @type {Array<ScaleQuestionUserAnswerItem>}
     * @memberof ScaleQuestionUserAnswerRegisterRequest
     */
    items: Array<ScaleQuestionUserAnswerItem>;
}

/**
 * Check if a given object implements the ScaleQuestionUserAnswerRegisterRequest interface.
 */
export function instanceOfScaleQuestionUserAnswerRegisterRequest(value: object): value is ScaleQuestionUserAnswerRegisterRequest {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ScaleQuestionUserAnswerRegisterRequestFromJSON(json: any): ScaleQuestionUserAnswerRegisterRequest {
    return ScaleQuestionUserAnswerRegisterRequestFromJSONTyped(json, false);
}

export function ScaleQuestionUserAnswerRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScaleQuestionUserAnswerRegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ScaleQuestionUserAnswerItemFromJSON)),
    };
}

export function ScaleQuestionUserAnswerRegisterRequestToJSON(json: any): ScaleQuestionUserAnswerRegisterRequest {
    return ScaleQuestionUserAnswerRegisterRequestToJSONTyped(json, false);
}

export function ScaleQuestionUserAnswerRegisterRequestToJSONTyped(value?: ScaleQuestionUserAnswerRegisterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ScaleQuestionUserAnswerItemToJSON)),
    };
}

