/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScaleQuestionDto } from './ScaleQuestionDto';
import {
    ScaleQuestionDtoFromJSON,
    ScaleQuestionDtoFromJSONTyped,
    ScaleQuestionDtoToJSON,
    ScaleQuestionDtoToJSONTyped,
} from './ScaleQuestionDto';

/**
 * 척도 질문 목록 조회 응답
 * @export
 * @interface ScaleQuestionFindAllResponse
 */
export interface ScaleQuestionFindAllResponse {
    /**
     * 척도 질문 목록
     * @type {Array<ScaleQuestionDto>}
     * @memberof ScaleQuestionFindAllResponse
     */
    scaleQuestions: Array<ScaleQuestionDto>;
}

/**
 * Check if a given object implements the ScaleQuestionFindAllResponse interface.
 */
export function instanceOfScaleQuestionFindAllResponse(value: object): value is ScaleQuestionFindAllResponse {
    if (!('scaleQuestions' in value) || value['scaleQuestions'] === undefined) return false;
    return true;
}

export function ScaleQuestionFindAllResponseFromJSON(json: any): ScaleQuestionFindAllResponse {
    return ScaleQuestionFindAllResponseFromJSONTyped(json, false);
}

export function ScaleQuestionFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScaleQuestionFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'scaleQuestions': ((json['scaleQuestions'] as Array<any>).map(ScaleQuestionDtoFromJSON)),
    };
}

export function ScaleQuestionFindAllResponseToJSON(json: any): ScaleQuestionFindAllResponse {
    return ScaleQuestionFindAllResponseToJSONTyped(json, false);
}

export function ScaleQuestionFindAllResponseToJSONTyped(value?: ScaleQuestionFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scaleQuestions': ((value['scaleQuestions'] as Array<any>).map(ScaleQuestionDtoToJSON)),
    };
}

