/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 회원가입 응답
 * @export
 * @interface UserRegisterResponse
 */
export interface UserRegisterResponse {
    /**
     * 새로 발급된 JWT 액세스 토큰
     * @type {string}
     * @memberof UserRegisterResponse
     */
    accessToken: string;
}

/**
 * Check if a given object implements the UserRegisterResponse interface.
 */
export function instanceOfUserRegisterResponse(value: object): value is UserRegisterResponse {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    return true;
}

export function UserRegisterResponseFromJSON(json: any): UserRegisterResponse {
    return UserRegisterResponseFromJSONTyped(json, false);
}

export function UserRegisterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegisterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
    };
}

export function UserRegisterResponseToJSON(json: any): UserRegisterResponse {
    return UserRegisterResponseToJSONTyped(json, false);
}

export function UserRegisterResponseToJSONTyped(value?: UserRegisterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
    };
}

