/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 회원가입 요청
 * @export
 * @interface UserRegisterRequest
 */
export interface UserRegisterRequest {
    /**
     * 이름
     * @type {string}
     * @memberof UserRegisterRequest
     */
    name: string;
    /**
     * 역할 (USER, ADMIN)
     * @type {string}
     * @memberof UserRegisterRequest
     */
    role: UserRegisterRequestRoleEnum;
    /**
     * 성별 (MALE, FEMALE)
     * @type {string}
     * @memberof UserRegisterRequest
     */
    gender: UserRegisterRequestGenderEnum;
    /**
     * 생년월일
     * @type {Date}
     * @memberof UserRegisterRequest
     */
    birthDate: Date;
    /**
     * 주소
     * @type {string}
     * @memberof UserRegisterRequest
     */
    address: string;
    /**
     * [환자 정보] 주 진단명
     * @type {string}
     * @memberof UserRegisterRequest
     */
    primaryDiagnosis?: string;
    /**
     * [환자 정보] 학력 (발병 전)
     * @type {string}
     * @memberof UserRegisterRequest
     */
    educationBeforeOnset?: string;
    /**
     * [환자 정보] 병력 - 진단명 (과거 진단명)
     * @type {string}
     * @memberof UserRegisterRequest
     */
    previousDiagnosis?: string;
    /**
     * [환자 정보] 병력 - 진단받은 시기
     * @type {string}
     * @memberof UserRegisterRequest
     */
    diagnosisYearMonth?: string;
    /**
     * [환자 정보] 병력 - 진단받은 병원
     * @type {string}
     * @memberof UserRegisterRequest
     */
    diagnosisHospital?: string;
    /**
     * [환자 정보] 주증상
     * @type {string}
     * @memberof UserRegisterRequest
     */
    chiefComplaint?: string;
    /**
     * [환자 정보] 현재 주로 이용하는 병원
     * @type {string}
     * @memberof UserRegisterRequest
     */
    currentHospital?: string;
    /**
     * [환자 정보] 현재 거주하는 장소
     * @type {string}
     * @memberof UserRegisterRequest
     */
    currentResidence?: string;
    /**
     * [환자 정보] 의료보장 (HEALTH_INSURANCE: 건강보험, MEDICAL_AID_1: 의료급여 1종, MEDICAL_AID_2: 의료급여 2종, NEAR_POOR_1: 차상위 1종, NEAR_POOR_2: 차상위 2종)
     * @type {string}
     * @memberof UserRegisterRequest
     */
    medicalCoverage?: UserRegisterRequestMedicalCoverageEnum;
    /**
     * [환자 정보] 산정특례 등록 여부
     * @type {boolean}
     * @memberof UserRegisterRequest
     */
    specialCaseRegistered?: boolean;
    /**
     * [환자 정보] 산정특례 등록일 (산정특례 등록 시 필수)
     * @type {Date}
     * @memberof UserRegisterRequest
     */
    specialCaseRegisteredDate?: Date;
    /**
     * [환자 정보] 장애 등록 여부
     * @type {boolean}
     * @memberof UserRegisterRequest
     */
    disabilityRegistered?: boolean;
    /**
     * [환자 정보] 장애 등록 진행 상태 (REGISTERED: 등록, IN_PROGRESS: 진행 중, NOT_REGISTERED: 미등록)
     * @type {string}
     * @memberof UserRegisterRequest
     */
    disabilityStatus?: UserRegisterRequestDisabilityStatusEnum;
    /**
     * [환자 정보] 장애 종류 (장애 등록 시 필수)
     * @type {string}
     * @memberof UserRegisterRequest
     */
    disabilityType?: string;
    /**
     * [환자 정보] 장애 정도 (SEVERE: 심한 장애, NOT_SEVERE: 심하지 않은 장애)
     * @type {string}
     * @memberof UserRegisterRequest
     */
    disabilitySeverity?: UserRegisterRequestDisabilitySeverityEnum;
    /**
     * [환자 정보] 사회복지서비스 (다중 선택)
     * @type {Array<string>}
     * @memberof UserRegisterRequest
     */
    socialWelfareServiceLabels?: Array<string>;
}


/**
 * @export
 */
export const UserRegisterRequestRoleEnum = {
    User: 'USER',
    Admin: 'ADMIN'
} as const;
export type UserRegisterRequestRoleEnum = typeof UserRegisterRequestRoleEnum[keyof typeof UserRegisterRequestRoleEnum];

/**
 * @export
 */
export const UserRegisterRequestGenderEnum = {
    Male: 'MALE',
    Female: 'FEMALE'
} as const;
export type UserRegisterRequestGenderEnum = typeof UserRegisterRequestGenderEnum[keyof typeof UserRegisterRequestGenderEnum];

/**
 * @export
 */
export const UserRegisterRequestMedicalCoverageEnum = {
    HealthInsurance: 'HEALTH_INSURANCE',
    MedicalAid1: 'MEDICAL_AID_1',
    MedicalAid2: 'MEDICAL_AID_2',
    NearPoor1: 'NEAR_POOR_1',
    NearPoor2: 'NEAR_POOR_2'
} as const;
export type UserRegisterRequestMedicalCoverageEnum = typeof UserRegisterRequestMedicalCoverageEnum[keyof typeof UserRegisterRequestMedicalCoverageEnum];

/**
 * @export
 */
export const UserRegisterRequestDisabilityStatusEnum = {
    Registered: 'REGISTERED',
    InProgress: 'IN_PROGRESS',
    NotRegistered: 'NOT_REGISTERED'
} as const;
export type UserRegisterRequestDisabilityStatusEnum = typeof UserRegisterRequestDisabilityStatusEnum[keyof typeof UserRegisterRequestDisabilityStatusEnum];

/**
 * @export
 */
export const UserRegisterRequestDisabilitySeverityEnum = {
    Severe: 'SEVERE',
    NotSevere: 'NOT_SEVERE'
} as const;
export type UserRegisterRequestDisabilitySeverityEnum = typeof UserRegisterRequestDisabilitySeverityEnum[keyof typeof UserRegisterRequestDisabilitySeverityEnum];


/**
 * Check if a given object implements the UserRegisterRequest interface.
 */
export function instanceOfUserRegisterRequest(value: object): value is UserRegisterRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('gender' in value) || value['gender'] === undefined) return false;
    if (!('birthDate' in value) || value['birthDate'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function UserRegisterRequestFromJSON(json: any): UserRegisterRequest {
    return UserRegisterRequestFromJSONTyped(json, false);
}

export function UserRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'role': json['role'],
        'gender': json['gender'],
        'birthDate': (new Date(json['birthDate'])),
        'address': json['address'],
        'primaryDiagnosis': json['primaryDiagnosis'] == null ? undefined : json['primaryDiagnosis'],
        'educationBeforeOnset': json['educationBeforeOnset'] == null ? undefined : json['educationBeforeOnset'],
        'previousDiagnosis': json['previousDiagnosis'] == null ? undefined : json['previousDiagnosis'],
        'diagnosisYearMonth': json['diagnosisYearMonth'] == null ? undefined : json['diagnosisYearMonth'],
        'diagnosisHospital': json['diagnosisHospital'] == null ? undefined : json['diagnosisHospital'],
        'chiefComplaint': json['chiefComplaint'] == null ? undefined : json['chiefComplaint'],
        'currentHospital': json['currentHospital'] == null ? undefined : json['currentHospital'],
        'currentResidence': json['currentResidence'] == null ? undefined : json['currentResidence'],
        'medicalCoverage': json['medicalCoverage'] == null ? undefined : json['medicalCoverage'],
        'specialCaseRegistered': json['specialCaseRegistered'] == null ? undefined : json['specialCaseRegistered'],
        'specialCaseRegisteredDate': json['specialCaseRegisteredDate'] == null ? undefined : (new Date(json['specialCaseRegisteredDate'])),
        'disabilityRegistered': json['disabilityRegistered'] == null ? undefined : json['disabilityRegistered'],
        'disabilityStatus': json['disabilityStatus'] == null ? undefined : json['disabilityStatus'],
        'disabilityType': json['disabilityType'] == null ? undefined : json['disabilityType'],
        'disabilitySeverity': json['disabilitySeverity'] == null ? undefined : json['disabilitySeverity'],
        'socialWelfareServiceLabels': json['socialWelfareServiceLabels'] == null ? undefined : json['socialWelfareServiceLabels'],
    };
}

export function UserRegisterRequestToJSON(json: any): UserRegisterRequest {
    return UserRegisterRequestToJSONTyped(json, false);
}

export function UserRegisterRequestToJSONTyped(value?: UserRegisterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'role': value['role'],
        'gender': value['gender'],
        'birthDate': value['birthDate'].toISOString().substring(0,10),
        'address': value['address'],
        'primaryDiagnosis': value['primaryDiagnosis'],
        'educationBeforeOnset': value['educationBeforeOnset'],
        'previousDiagnosis': value['previousDiagnosis'],
        'diagnosisYearMonth': value['diagnosisYearMonth'],
        'diagnosisHospital': value['diagnosisHospital'],
        'chiefComplaint': value['chiefComplaint'],
        'currentHospital': value['currentHospital'],
        'currentResidence': value['currentResidence'],
        'medicalCoverage': value['medicalCoverage'],
        'specialCaseRegistered': value['specialCaseRegistered'],
        'specialCaseRegisteredDate': value['specialCaseRegisteredDate'] == null ? value['specialCaseRegisteredDate'] : value['specialCaseRegisteredDate'].toISOString().substring(0,10),
        'disabilityRegistered': value['disabilityRegistered'],
        'disabilityStatus': value['disabilityStatus'],
        'disabilityType': value['disabilityType'],
        'disabilitySeverity': value['disabilitySeverity'],
        'socialWelfareServiceLabels': value['socialWelfareServiceLabels'],
    };
}

