/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 사용자 척도 점수 항목
 * @export
 * @interface UserScaleItem
 */
export interface UserScaleItem {
    /**
     * 척도 카테고리 (ANXIETY, DEPRESSION, ANGER)
     * @type {string}
     * @memberof UserScaleItem
     */
    scaleCategory: UserScaleItemScaleCategoryEnum;
    /**
     * 척도 점수
     * @type {number}
     * @memberof UserScaleItem
     */
    score: number;
}


/**
 * @export
 */
export const UserScaleItemScaleCategoryEnum = {
    Anxiety: 'ANXIETY',
    Depression: 'DEPRESSION',
    Anger: 'ANGER'
} as const;
export type UserScaleItemScaleCategoryEnum = typeof UserScaleItemScaleCategoryEnum[keyof typeof UserScaleItemScaleCategoryEnum];


/**
 * Check if a given object implements the UserScaleItem interface.
 */
export function instanceOfUserScaleItem(value: object): value is UserScaleItem {
    if (!('scaleCategory' in value) || value['scaleCategory'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function UserScaleItemFromJSON(json: any): UserScaleItem {
    return UserScaleItemFromJSONTyped(json, false);
}

export function UserScaleItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserScaleItem {
    if (json == null) {
        return json;
    }
    return {
        
        'scaleCategory': json['scaleCategory'],
        'score': json['score'],
    };
}

export function UserScaleItemToJSON(json: any): UserScaleItem {
    return UserScaleItemToJSONTyped(json, false);
}

export function UserScaleItemToJSONTyped(value?: UserScaleItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scaleCategory': value['scaleCategory'],
        'score': value['score'],
    };
}

