/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 복지 서비스 항목
 * @export
 * @interface WelfareServiceItem
 */
export interface WelfareServiceItem {
    /**
     * 서비스명
     * @type {string}
     * @memberof WelfareServiceItem
     */
    serviceName: string;
    /**
     * 서비스 상세 링크
     * @type {string}
     * @memberof WelfareServiceItem
     */
    serviceDetailLink: string;
    /**
     * 서비스 요약 설명
     * @type {string}
     * @memberof WelfareServiceItem
     */
    serviceDigest?: string;
}

/**
 * Check if a given object implements the WelfareServiceItem interface.
 */
export function instanceOfWelfareServiceItem(value: object): value is WelfareServiceItem {
    if (!('serviceName' in value) || value['serviceName'] === undefined) return false;
    if (!('serviceDetailLink' in value) || value['serviceDetailLink'] === undefined) return false;
    return true;
}

export function WelfareServiceItemFromJSON(json: any): WelfareServiceItem {
    return WelfareServiceItemFromJSONTyped(json, false);
}

export function WelfareServiceItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): WelfareServiceItem {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceName': json['serviceName'],
        'serviceDetailLink': json['serviceDetailLink'],
        'serviceDigest': json['serviceDigest'] == null ? undefined : json['serviceDigest'],
    };
}

export function WelfareServiceItemToJSON(json: any): WelfareServiceItem {
    return WelfareServiceItemToJSONTyped(json, false);
}

export function WelfareServiceItemToJSONTyped(value?: WelfareServiceItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceName': value['serviceName'],
        'serviceDetailLink': value['serviceDetailLink'],
        'serviceDigest': value['serviceDigest'],
    };
}

