/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommonResponseHomeResponse,
} from '../models/index';
import {
    CommonResponseHomeResponseFromJSON,
    CommonResponseHomeResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class HomeApi extends runtime.BaseAPI {

    /**
     * 사용자의 홈 화면에 표시될 정보를 조회합니다. 월별/연간 일기 수, 감정 통계, 추천 복지 서비스, 척도 질문 필요 여부 등을 포함합니다.
     * 홈 화면 정보 조회
     */
    async getHomeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseHomeResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/home`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseHomeResponseFromJSON(jsonValue));
    }

    /**
     * 사용자의 홈 화면에 표시될 정보를 조회합니다. 월별/연간 일기 수, 감정 통계, 추천 복지 서비스, 척도 질문 필요 여부 등을 포함합니다.
     * 홈 화면 정보 조회
     */
    async getHome(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseHomeResponse> {
        const response = await this.getHomeRaw(initOverrides);
        return await response.value();
    }

}
