/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommonResponseScaleQuestionFindAllResponse,
  CommonResponseUnit,
  CommonResponseUserScaleFindAllResponse,
  ScaleQuestionUserAnswerRegisterRequest,
} from '../models/index';
import {
    CommonResponseScaleQuestionFindAllResponseFromJSON,
    CommonResponseScaleQuestionFindAllResponseToJSON,
    CommonResponseUnitFromJSON,
    CommonResponseUnitToJSON,
    CommonResponseUserScaleFindAllResponseFromJSON,
    CommonResponseUserScaleFindAllResponseToJSON,
    ScaleQuestionUserAnswerRegisterRequestFromJSON,
    ScaleQuestionUserAnswerRegisterRequestToJSON,
} from '../models/index';

export interface RegisterUserScaleQuestionResultRequest {
    scaleQuestionUserAnswerRegisterRequest: ScaleQuestionUserAnswerRegisterRequest;
}

/**
 * 
 */
export class ScaleQuestionApi extends runtime.BaseAPI {

    /**
     * 시스템에 등록된 모든 척도 질문을 조회합니다. 불안, 우울, 분노 카테고리별 질문을 포함합니다.
     * 전체 척도 질문 목록 조회
     */
    async findAllScaleQuestionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseScaleQuestionFindAllResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/scale-questions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseScaleQuestionFindAllResponseFromJSON(jsonValue));
    }

    /**
     * 시스템에 등록된 모든 척도 질문을 조회합니다. 불안, 우울, 분노 카테고리별 질문을 포함합니다.
     * 전체 척도 질문 목록 조회
     */
    async findAllScaleQuestions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseScaleQuestionFindAllResponse> {
        const response = await this.findAllScaleQuestionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * 현재 사용자의 모든 척도 측정 결과를 조회합니다. 회차별로 그룹화된 결과를 반환합니다.
     * 사용자 척도 결과 조회
     */
    async findAllUserScalesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseUserScaleFindAllResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/users/scales`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseUserScaleFindAllResponseFromJSON(jsonValue));
    }

    /**
     * 현재 사용자의 모든 척도 측정 결과를 조회합니다. 회차별로 그룹화된 결과를 반환합니다.
     * 사용자 척도 결과 조회
     */
    async findAllUserScales(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseUserScaleFindAllResponse> {
        const response = await this.findAllUserScalesRaw(initOverrides);
        return await response.value();
    }

    /**
     * 사용자의 척도 질문에 대한 응답을 등록합니다. 불안, 우울, 분노 척도에 대한 응답을 포함합니다.
     * 척도 질문 응답 등록
     */
    async registerUserScaleQuestionResultRaw(requestParameters: RegisterUserScaleQuestionResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseUnit>> {
        if (requestParameters['scaleQuestionUserAnswerRegisterRequest'] == null) {
            throw new runtime.RequiredError(
                'scaleQuestionUserAnswerRegisterRequest',
                'Required parameter "scaleQuestionUserAnswerRegisterRequest" was null or undefined when calling registerUserScaleQuestionResult().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/users/scale-questions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScaleQuestionUserAnswerRegisterRequestToJSON(requestParameters['scaleQuestionUserAnswerRegisterRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseUnitFromJSON(jsonValue));
    }

    /**
     * 사용자의 척도 질문에 대한 응답을 등록합니다. 불안, 우울, 분노 척도에 대한 응답을 포함합니다.
     * 척도 질문 응답 등록
     */
    async registerUserScaleQuestionResult(requestParameters: RegisterUserScaleQuestionResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseUnit> {
        const response = await this.registerUserScaleQuestionResultRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
