/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommonResponseCurrentUserResponse,
  CommonResponseUserRegisterResponse,
  UserRegisterRequest,
} from '../models/index';
import {
    CommonResponseCurrentUserResponseFromJSON,
    CommonResponseCurrentUserResponseToJSON,
    CommonResponseUserRegisterResponseFromJSON,
    CommonResponseUserRegisterResponseToJSON,
    UserRegisterRequestFromJSON,
    UserRegisterRequestToJSON,
} from '../models/index';

export interface RegisterRequest {
    userRegisterRequest: UserRegisterRequest;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * 현재 로그인한 사용자의 상세 정보를 조회합니다.
     * 현재 사용자 정보 조회
     */
    async getMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseCurrentUserResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/users/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseCurrentUserResponseFromJSON(jsonValue));
    }

    /**
     * 현재 로그인한 사용자의 상세 정보를 조회합니다.
     * 현재 사용자 정보 조회
     */
    async getMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseCurrentUserResponse> {
        const response = await this.getMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * OAuth2 인증 후 사용자 상세 정보를 등록합니다. 이름, 역할, 성별, 생년월일, 주소 및 의료 관련 정보를 포함합니다.
     * 회원가입
     */
    async registerRaw(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseUserRegisterResponse>> {
        if (requestParameters['userRegisterRequest'] == null) {
            throw new runtime.RequiredError(
                'userRegisterRequest',
                'Required parameter "userRegisterRequest" was null or undefined when calling register().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/users/register`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserRegisterRequestToJSON(requestParameters['userRegisterRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseUserRegisterResponseFromJSON(jsonValue));
    }

    /**
     * OAuth2 인증 후 사용자 상세 정보를 등록합니다. 이름, 역할, 성별, 생년월일, 주소 및 의료 관련 정보를 포함합니다.
     * 회원가입
     */
    async register(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseUserRegisterResponse> {
        const response = await this.registerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
